### ISSUE TITLE
Madrona was not compiled with CUDA support

### ISSUE THREAD

**Issue by zelaix** [shacklettbp/madrona_3d_example#3]
Hello, I followed the instructions to build the simulator on Linux and had no problem running with the CPU backend.
```
python scripts/train.py --num-worlds 1024 --num-updates 100 --ckpt-dir build/ckpts
```
However, I got the following error when added `--gpu-sim` to test the GPU backend.
```
madrona_escape_room/src/mgr.cpp:319 in static Manager::Impl *madEscape::Manager::Impl::init(const Manager::Config &, const viz::VizECSBridge *)
Madrona was not compiled with CUDA support
Aborted (core dumped)
```
My dependency is as follows
* Linux: Ubuntu 20.04
* GPU: NVIDIA GeForce RTX 3090
* CUDA version: 12.2
* cmake: 3.27.7
* python: 3.9
* pytorch: 2.1.0+cu12.1

Please give me some help, thank you.

**Comment by shacklettbp** [comment]
This most likely means you don't have a new enough version of the CUDA toolkit installed (or cmake can't find it). Did you install cuda 12?: https://developer.nvidia.com/cuda-downloads Note that if you're just looking at nvidia-smi, the version of CUDA printed there just reflects driver compatibility, you need to install the userspace components still.

**Comment by zelaix** [comment]
The problem is solved after I installed cuda 12. Thanks!
